### ISSUE TITLE
I wonder what are benefits of this if it's larger than ruby:alpine?

### ISSUE THREAD

**Issue by Nakilon** [unasuke/distroless-ruby#1]
```
$ docker image inspect unasuke/distroless-ruby | grep Size
        "Size": 59420950,
        "VirtualSize": 59420950,
$ docker image inspect ruby:alpine | grep Size
        "Size": 56740679,
        "VirtualSize": 56740679,
```

Launch time

```
$ time docker run --rm -it unasuke/distroless-ruby ruby -v
```

is the same as ruby:alpine.

**Comment by Atem18** [comment]
@Nakilon security ?

**Comment by unasuke** [comment]
Thanks for the comments. It's described in distroless original repository.

> Restricting what's in your runtime container to precisely what's necessary for your app is a best practice employed by Google and other tech giants that have used containers in production for many years. It improves the signal to noise of scanners (e.g. CVE) and reduces the burden of establishing provenance to just what you need.

https://github.com/GoogleContainerTools/distroless#why-should-i-use-distroless-images
